site_name: IAW Jose

nav:
    - Principal: index.md
    - Acerca de: about.md
    - Práctica 01: Practica-01.md
    - Práctica 08: Practica-08.md

theme: 
    name: material
    palette:
        primary: purple
    font:
        code: Montserrat
    language: es
    logo: images/logo.png
