site_name: IAW Jose

nav:
    - Principal: index.md
    - Acerca de: about.md
    - Práctica 01: Practica-01.md
    - Práctica 03: Practica-03.md

theme: 
    name: material
    palette:
        primary: purple
    font:
        code: Montserrat
    language: es
    logo: images/logo.png
    features:
        - navigation.tabs